FROM mcr.microsoft.com / dotnet / sdk:8.0 AS build
WORKDIR /src
COPY . ./OrderService.API
COPY ../OrderService.Application ./OrderService.Application
COPY ../OrderService.Infrastructure ./OrderService.Infrastructure
COPY ../OrderService.Domain ./OrderService.Domain
RUN dotnet restore OrderService.API/OrderService.API.csproj \
&& dotnet publish OrderService.API/OrderService.API.csproj -c Release -o /app/publish


FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8081
ENV ASPNETCORE_URLS=http://+:8081
ENTRYPOINT["dotnet", "OrderService.API.dll"]