name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test (coverage >= 80%)
        run: |
          dotnet test \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=cobertura \
            /p:Threshold=80 \
            /p:ThresholdType=line

  docker-build:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # (Opcional) Login a GHCR si quieres publicar imágenes
      # - name: Login to GHCR
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ProductService image
        uses: docker/build-push-action@v6
        with:
          context: ./services/ProductService/ProductService.API
          file: ./services/ProductService/ProductService.API/Dockerfile
          push: false
          tags: productservice:local

      - name: Build OrderService image
        uses: docker/build-push-action@v6
        with:
          context: ./services/OrderService/OrderService.API
          file: ./services/OrderService/OrderService.API/Dockerfile
          push: false
          tags: orderservice:local
